import type { Attribute, CustomElementDeclaration, Package } from './manifest.js';

export interface StoriesOptions {
    /**
     * Module specifier imported at the top of each story so the element registers
     * itself. Defaults to `./<tag>.js`. `{tag}` is substituted with the tag name.
     * Treated as trusted build config — it becomes the generated `import` target,
     * so don't derive it from untrusted input (security-findings #29).
     */
    importPath?: string;
}

/** A Storybook `argTypes` control entry derived from one attribute. */
interface ArgType {
    control: string | { type: string };
    options?: string[];
    description?: string;
}

/** Maps an attribute to a Storybook control, using captured union values as `select` options. */
function controlFor(attr: Attribute): ArgType {
    const argType: ArgType =
        attr.values?.length
            ? { control: { type: 'select' }, options: attr.values }
            : attr.type?.text === 'boolean'
              ? { control: 'boolean' }
              : attr.type?.text === 'number'
                ? { control: 'number' }
                : { control: 'text' };
    if (attr.description) argType.description = attr.description;
    return argType;
}

/** Coerces an attribute's source-text default (e.g. `'md'`, `false`, `5`) to a real JS value. */
function defaultValue(attr: Attribute): unknown {
    const raw = attr.default?.trim();
    if (raw === undefined || raw === '') return undefined;
    const quoted = /^(['"])([\s\S]*)\1$/.exec(raw);
    if (quoted) return quoted[2];
    if (raw === 'true' || raw === 'false') return raw === 'true';
    if (/^-?\d+(\.\d+)?$/.test(raw)) return Number(raw);
    return undefined; // non-literal initializer (expression) — leave unset
}

/** Indents every line of a multi-line value (e.g. a JSON block) to sit inside the object literal. */
function indent(block: string, spaces: string): string {
    return block.replace(/\n/g, `\n${spaces}`);
}

/** The conventional file name for a component's stories: `<tag>.stories.js`. */
export function storiesFileName(decl: CustomElementDeclaration): string {
    return `${decl.tagName}.stories.js`;
}

/**
 * Generates a Storybook [Component Story Format](https://storybook.js.org/docs/api/csf)
 * module for a custom element: an `argTypes` controls panel derived from the
 * element's attributes (string-literal unions become `select` options) and
 * events (mapped to Storybook actions), plus a default story that applies the
 * args as attributes. Zero hand-written story code required.
 *
 * All interpolated identifiers go through `JSON.stringify`, so the output is safe
 * as a standalone `.js` file even for unusual tag/attribute/event names. (Do not
 * inline the result into an HTML `<script>` — a name containing `</script>` would
 * then break out; security-findings #26.)
 */
export function toStories(decl: CustomElementDeclaration, options: StoriesOptions = {}): string {
    const tag = decl.tagName!;
    const importPath = (options.importPath ?? './{tag}.js').replace(/\{tag\}/g, tag);

    const argTypes: Record<string, ArgType | { action: string }> = {};
    for (const attr of decl.attributes ?? []) argTypes[attr.name] = controlFor(attr);
    for (const event of decl.events ?? []) argTypes[event.name] = { action: event.name };

    const args: Record<string, unknown> = {};
    for (const attr of decl.attributes ?? []) {
        const value = defaultValue(attr);
        if (value !== undefined) args[attr.name] = value;
    }

    return `// Generated by banira from the Custom Elements Manifest. Do not edit by hand.
import ${JSON.stringify(importPath)};

/** @type {import('@storybook/web-components').Meta} */
export default {
  title: ${JSON.stringify(`Components/${tag}`)},
  component: ${JSON.stringify(tag)},
  tags: ['autodocs'],
  argTypes: ${indent(JSON.stringify(argTypes, null, 2), '  ')},
  args: ${indent(JSON.stringify(args, null, 2), '  ')},
  render: (args) => {
    const el = document.createElement(${JSON.stringify(tag)});
    for (const [name, value] of Object.entries(args)) {
      if (value === undefined || value === null || value === false) continue;
      el.setAttribute(name, value === true ? '' : String(value));
    }
    return el;
  },
};

export const Default = {};
`;
}

/** Generates a `[fileName, source]` pair of Storybook stories for every custom element in a manifest. */
export function manifestToStories(pkg: Package, options: StoriesOptions = {}): { fileName: string; source: string }[] {
    return pkg.modules
        .flatMap((m) => m.declarations)
        .filter((d): d is CustomElementDeclaration => Boolean(d.tagName))
        .map((decl) => ({ fileName: storiesFileName(decl), source: toStories(decl, options) }));
}
