import type { ClassField, ClassMethod, CustomElementDeclaration, Package } from './manifest.js';

export interface TypeShimOptions {
    /** Also augment `JSX.IntrinsicElements` so the tags type-check in JSX/TSX (default false). */
    jsx?: boolean;
}

/** A safe TypeScript interface name derived from a custom element declaration. */
function interfaceName(decl: CustomElementDeclaration): string {
    const base = decl.name && /^[A-Za-z_$][\w$]*$/.test(decl.name)
        ? decl.name
        : (decl.tagName ?? 'Unknown')
              .split(/[^A-Za-z0-9]+/)
              .filter(Boolean)
              .map((s) => s[0]!.toUpperCase() + s.slice(1))
              .join('');
    return `${base}Element`;
}

function docComment(description: string | undefined, deprecated: boolean | string | undefined, indent: string): string {
    const lines: string[] = [];
    if (description) lines.push(...description.split(/\r?\n/));
    if (deprecated !== undefined) lines.push(`@deprecated${typeof deprecated === 'string' ? ` ${deprecated}` : ''}`);
    if (lines.length === 0) return '';
    if (lines.length === 1) return `${indent}/** ${lines[0]} */\n`;
    return `${indent}/**\n${lines.map((l) => `${indent} * ${l}`).join('\n')}\n${indent} */\n`;
}

function fieldMember(field: ClassField): string {
    const doc = docComment(field.description, field.deprecated, '  ');
    const ro = field.readonly ? 'readonly ' : '';
    const type = field.type?.text ?? 'unknown';
    return `${doc}  ${ro}${field.name}: ${type};`;
}

function methodMember(method: ClassMethod): string {
    const doc = docComment(method.description, method.deprecated, '  ');
    const params = (method.parameters ?? [])
        .map((p) => `${p.rest ? '...' : ''}${p.name}${p.optional && !p.rest ? '?' : ''}: ${p.type?.text ?? 'unknown'}`)
        .join(', ');
    const ret = method.return?.type?.text ?? 'void';
    return `${doc}  ${method.name}(${params}): ${ret};`;
}

function declarationInterface(decl: CustomElementDeclaration): string {
    const name = interfaceName(decl);
    const members = (decl.members ?? [])
        .filter((m) => !m.inheritedFrom)
        .map((m) => (m.kind === 'field' ? fieldMember(m) : methodMember(m)));
    const body = members.length ? `\n${members.join('\n')}\n` : '';
    const doc = docComment(decl.description ?? decl.summary, decl.deprecated, '');
    return `${doc}export interface ${name} extends HTMLElement {${body}}`;
}

/**
 * Generates a self-contained `.d.ts` from a Custom Elements Manifest: one
 * `HTMLElement`-extending interface per custom element plus an
 * `HTMLElementTagNameMap` augmentation, so `document.querySelector('my-el')`
 * and `document.createElement('my-el')` are correctly typed with no runtime
 * import. With `{ jsx: true }` it also augments `JSX.IntrinsicElements`.
 */
export function toTypeDefinitions(pkg: Package, options: TypeShimOptions = {}): string {
    const decls = pkg.modules.flatMap((m) => m.declarations).filter((d) => d.tagName);

    const interfaces = decls.map(declarationInterface);
    const tagMap = decls.map((d) => `    '${d.tagName}': ${interfaceName(d)};`).join('\n');

    const globalBlocks = [`  interface HTMLElementTagNameMap {\n${tagMap}\n  }`];
    if (options.jsx) {
        const jsxMap = decls
            .map((d) => `      '${d.tagName}': Partial<${interfaceName(d)}> & { [attr: string]: unknown };`)
            .join('\n');
        globalBlocks.push(`  namespace JSX {\n    interface IntrinsicElements {\n${jsxMap}\n    }\n  }`);
    }

    return [
        '// Generated by banira from the Custom Elements Manifest. Do not edit by hand.',
        '',
        interfaces.join('\n\n'),
        '',
        `declare global {\n${globalBlocks.join('\n\n')}\n}`,
        '',
        'export {};',
        '',
    ].join('\n');
}
